version: '3.1'
services:
  web:
    image: odoo:16.0
    depends_on:
      - db_16
    ports:
      - "8069:8069"
    environment:
      - HOST=db_16
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo_web_data_16:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db_16:
    image: postgres:15
    environment:
      # Consider explicitly defining the password here for clarity
      - POSTGRES_DB=odoo_16
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
    ports:
      - "5433:5432"
    volumes:
      - postgresql-odo-16:/var/lib/postgresql
      - postgresql_data-16:/var/lib/postgresql/data
    secrets:
      - postgresql_password
  pgadmin:
    # Assuming you still want pgadmin
    container_name: pgadmin_odoo_16
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5081:80"

volumes:
  odoo_web_data_16:
  postgresql-odo-16:
  postgresql_data-16:


secrets:
  postgresql_password:
    file: odoo_pg_pass.txt
